import { Beiruti } from "next/font/google";
import "./globals.css";
import Header from "./components/header";


// If loading a variable font, you don't need to specify the font weight
const beiruti = Beiruti({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-beiruti",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${beiruti.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
